### ISSUE TITLE
-Wmaybe-uninitialized variable numEdgeIdxPerFace @ src/fg_geometry.c

### ISSUE THREAD

**Issue by genbtc** [FreeGLUTProject/freeglut#107]
During a normal build of Freeglut-3.2.2 on gentoo, we get a warning that could potentially result in an error.

src/fg_geometry.c:605:13: warning: 'numEdgeIdxPerFace' may be used uninitialized in this function [-Wmaybe-uninitialized]
https://github.com/FreeGLUTProject/freeglut/blob/master/src/fg_geometry.c#L613=
in the fghGenerateGeometryWithIndexArray() function.

**Description of the bug:**
It starts with an uninitialized variable,
Assigns the variable in a switch/case statement that has no default,
Then attempts to use it in a loop at the end of the function.

**Analysis:**
It may be a low priority, but I consider -Wmaybe-uninitialized to be worth the time to deal with.
The variable should be strictly initialized, not assumed to be initialized.
After some code review with another gentoo mentor, I have decided to submit an issue for this.

[Build.log](https://dpaste.com/2UN44YUD4)
Compiler used: GCC-11.2.1
related Compiler flags: -Wall -pedantic (comes from freeglut's build system)

On an unrelated note, you can see in the log, the only other warning is, there is a lot of spam from [-Wunused-const-variable=] coming from fg_font_data.c , if something could be done about this also, that would be great.

Thanks!

**Comment by jtsiomb** [comment]
The warning is completely spurious, there is no way as the code stands, for `numEdgeIdxPerFace` to be used uninitialized.

`vertSamps` is initialized to null, and is only ever changed to be non-null in the cases where `numEdgeIdxPerFace` is also assigned a value. The only place where `numEdgeIdxPerFace` is used, is inside an `if(vertSamps)`.

**Comment by jtsiomb** [comment]
I fixed the unused variable warnings. It was just a bunch of unused font glyphs, declared static in `fg_font_data.c` which could be safely removed.
