### ISSUE TITLE
Need help with glutPostRedisplay with a given framerate

### ISSUE THREAD

**Issue by wini3d** [FreeGLUTProject/freeglut#109]
I'm trying to do an update on an array of 3d objects with a given framerate, say 60fps.

```
It works nicely if I just manually list the array of objects inside a function with the translation/movement update.. 
MoveObject(cube[0],x,y,z,)
MoveObject(cube[1],x,y,z,)
...
```

but not so much (crashes) when doing a for loop or other iteration.. 

```
for(i = 0; i<=3, i++)
  MoveObject(cube[i],x,yz,)
loop
```

How do I set it up so that the loop movement is completed or a function is called once before doing a postredisplay while at a certain frame rate?

**Comment by jtsiomb** [comment]
I don't know what any of what you posted here has to do with `glutPostRedisplay`. If you want to cap your updates to the monitor refresh rate, or an integer fraction of it, you can enable vsync (see: `swap_interval` extensions). If you want to fix your update rate to a specific arbitrary number, you can't do that precisely, but you can approximate it by timing how much your drawing takes on average and sleep for the remainder of the time.

Either way, this is not a freeglut bug, and this is a place for freeglut bug reports and feature requests. So I'm closing it.

**Comment by wini3d** [comment]
Thanks for the added info, I did figure this out.
