### ISSUE TITLE
Scroll Lock and other keys not triggering for glutKeyboardFunc

### ISSUE THREAD

**Issue by wini3d** [FreeGLUTProject/freeglut#115]
only in glutKeyboard**Up**Func, also Print Screen, NumLock and Pause/Break.

**Comment by dcnieho** [comment]
Please provide more details. They only function or they only do not function for glutKeyboardUpFunc? What happens with glutKeyboardFunc? Latest FreeGLUT version? Which OS (Exact version)? etc

**Comment by jtsiomb** [comment]
The `glutKeyboardFunc` callback reports "normal" keys which map to ASCII. None of the keys you mentioned fall into that category. Special keys are reported by the callback set with `glutSpecialFunc`. Most of the keys you listed however are *not* in the set of special keys supported by either the original GLUT or freeglut, the only exception being num lock which should be reported by the special callback as a freeglut-specific extension.

Closing this bug report as invalid, originating in confusion about what `glutKeyboardFunc` does. If I misunderstood and there is a valid bug report here, please feel free to elaborate and I will re-open it.

**Comment by wini3d** [comment]
Thanks and will do.
