### ISSUE TITLE
[suggest] Keep the letter-case of `<pkg>` in IMPORTED target `<pkg>::<pkg>` the SAME.

### ISSUE THREAD

**Issue by hwhsu1231** [FreeGLUTProject/freeglut#116]
If the **IMPORTED** target name is provided in form of `<pkg>::<pkg>`, I think it is better to keep the letter-case of `<pkg>` the **SAME**, which means `freeglut::freeglut` or `FreeGLUT::FreeGLUT`. (BTW, I prefer the **FORMER**.)

For example:

- [`fmt::fmt`](https://github.com/fmtlib/fmt/blob/9.0.0/CMakeLists.txt#L232)
- [`spdlog::spdlog`](https://github.com/gabime/spdlog/blob/v1.10.0/CMakeLists.txt#L164)
- [`CLI11::CLI11`](https://github.com/CLIUtils/CLI11/blob/v2.2.0/CMakeLists.txt#L156)
- [`Catch2::Catch2`](https://github.com/catchorg/Catch2/blob/v3.1.0/src/CMakeLists.txt#L296)
- ...etc

**Comment by jtsiomb** [comment]
Can you provide some context? I don't know where this imported target name is defined. Also what is the significance of the first and second part of it?

**Comment by hwhsu1231** [comment]
The reasons why I suggest to do that is to:

- Keep **SYMMETRY** of the name form.
- Avoid writing the **WRONG** letter-case.

Because the original name is `FreeGLUT::freeglut` or `FreeGLUT::freeglut_static`.

**Comment by hwhsu1231** [comment]
The definition of the IMPORTED target name is related to the following codes (at least):

https://github.com/FreeGLUTProject/freeglut/blob/e3aa3d74f3c6a93b26fd66f81152d9c55506a6c6/CMakeLists.txt#L402-L407

https://github.com/FreeGLUTProject/freeglut/blob/e3aa3d74f3c6a93b26fd66f81152d9c55506a6c6/CMakeLists.txt#L629-L632

https://github.com/FreeGLUTProject/freeglut/blob/e3aa3d74f3c6a93b26fd66f81152d9c55506a6c6/CMakeLists.txt#L638-L642

**Comment by jtsiomb** [comment]
Ok I see.
I don't use cmake myself, and I have never used freeglut from a cmake project, so I don't know how this change would affect compatibility with existing projects. How would a cmake project use this namespace? Would it previously had to refer to freeglut as FreeGLUT::freeglut in their cmake file? And would it have to be modified to make it build again after this change?

Having said that, I'm not entierly sure it makes much sense to harmonize those two (namespace and library name), when the capitalized name will have to remain in the filenames themselves. It just shifts the inconsistency from one place to another.

Unfortunately when we converted to cmake, we failed to catch the inconsistency, so now we're pretty much stuck with it. If you want to be charitable you can find a way to rationalize it, like "it's the freeglut library, of the FreeGLUT project" :)

**Comment by hwhsu1231** [comment]
How about add it to the next MAJOR version?

At the beginning, the old and the new IMPORTED target coexist for a while. And then, deprecate the old one eventually.

**Comment by jtsiomb** [comment]
While not entirely unreasonable, I would not break compatibility just for aesthetics.

If this is left to me, before I make a decision about this I would have to make a few experiements with cmake projects, to see exactly what the effects of this change are. This will take a while.

Meanwhile, let's leave this open for discussion, in case someone else cares to give an opinion.

**Comment by dcnieho** [comment]
I'd say pure aesthetics are not worth the risk of breaking stuff on our end
or for users, given that freeglut's aim is stability

**Comment by jtsiomb** [comment]
I've thought about it, and dcnieho is absolutely right. This is such a minor thing, it's not even worth considering the possibility of breaking compatibility for it. Unless someone shows up with a detailed writeup about how this affects compatibility, and the result of that is tha it doesn't, I don't see this going forward. There are so many higher priority tasks, that I will not bother trying to figure this out myself. So I'll just go ahead and close this as a won't fix. If someone does volunteer to do the research, please either re-open, or post in the mailing list about it, and we'll reconsider.
