### ISSUE TITLE
Windows: incorrect colors for RGB contexts on 256 color display

### ISSUE THREAD

**Issue by jtsiomb** [FreeGLUTProject/freeglut#119]
On GNU/Linux or IRIX (X11/GLX), when running on 256 color mode (assuming OpenGL on such a mode is supported by hardware or mesa), the colors are approximately correct, with a dither pattern to hide the reduced color resolution. Under windows the colors are completely wrong. Presumably we need to set up a default 332 palette for RGB visuals when running on 256 color modes.

**Comment by jtsiomb** [comment]
Fixed in commit 564892281d34844edee39e54195c8e281b35ea76.

For reference here's before and after screenshots:

![win_8bpp_rgb_nopal](https://user-images.githubusercontent.com/2028446/188284852-b613f069-6198-4421-8ca2-5ddd459d4635.png)

![win_8bpp_rgb_332pal](https://user-images.githubusercontent.com/2028446/188284855-9ccd840c-0dfe-4842-b834-c0432425ef10.png)

**Comment by dcnieho** [comment]
Nice work!
