### ISSUE TITLE
Using wrong structure length

### ISSUE THREAD

**Issue by PopovEvgeniy** [FreeGLUTProject/freeglut#124]
Bug location: fghFillPFD in fg_window_mswin.c
Piece of problem code:

memset(ppfd, 0, sizeof *ppfd);
ppfd->nSize = sizeof *ppfd;

Fix:
memset(ppfd, 0, sizeof (ppfd));
ppfd->nSize = sizeof (ppfd);

**Comment by jtsiomb** [comment]
sizeof(ppfd) is the size of the pointer, either 4 or 8. We certainly don't want to use the size of the pointer here, but rather the size of the whole structure.
