### ISSUE TITLE
Single unit build file

### ISSUE THREAD

**Issue by j0ng4b** [FreeGLUTProject/freeglut#128]
I'm doing a project with all dependencies already included and for easily build there are a file thats include all freeglut source files. Some of this files has needed to be patched to fix redefinition errors (for example `fg_stroke_roman.c` and `fg_stroke_mono_roman.c`).

On the above example, I've only prefixed duplicated variables. On `fg_stroke_roman.c` is something like `StrokeRoman_<chxxxx>` and on `fg_stroke_mono_roman.c` is `StrokeMonoRoman_<chxxxx>`.

So, if I send a pull request with this patches there are any possibility of him get accepted?

**Comment by jtsiomb** [comment]
It depends on how extensive the changes are. If it's just a couple of variables in font files I don't see any harm in that. If it's taking every single static variable in freeglut and changing it from a short name to a long one I'd not want to make that change. Make your pull request and we can examine it on a case by case basis.

You might also find miniglut useful for what you're doing, which is a single-file GLUT subset. But its applicability depends on what set of GLUT features you're using: https://github.com/jtsiomb/miniglut

I'm closing this issue, if you decide to make the pull request, we can continue the discussion there about specific changes.
