### ISSUE TITLE
Freeglut osx 13

### ISSUE THREAD

**Issue by driofrio** [FreeGLUTProject/freeglut#131]
Dear friends, I have been using freeglut on mac for some time now, however since the mac os ventura has stopped working and when it is executed the message "failed to open display" appears and it doesn't even open Xquartz.
Before Ventura it worked fine.
I have tried both with freeglut 3.2.2 and with 3.4.
I am not testing on a mac M1 but on an Intel i7.
Any suggestions?

**Comment by jtsiomb** [comment]
Does it work if you start XQuartz manually before running it?

**Comment by driofrio** [comment]
Unfortunately no, look at the image, XQuartz is open and the message keeps
coming out.

[image: Captura de pantalla 2022-12-05 a la(s) 18.50.23.png]

And my Cmake is with this:
set(FREEGLUT_H /usr/local/Cellar/freeglut/3.4.0/include/)
include_directories(${FREEGLUT_H})

set(FREEGLUT_LINK /usr/local/Cellar/freeglut/3.4.0/lib/libglut.3.dylib)
link_libraries(${OPENGL} ${FREEGLUT_LINK})

Before Ventura, freeglut 3.2.2 worked fine.

**Comment by jtsiomb** [comment]
Since it does not start XQuartz automatically, there's a good chance it also does not set the `DISPLAY` environment variable automatically. Find out as which display XQuartz is running when started manually (usually it should be `:0.0`, but with MacOS X who knows), and set the `DISPLAY` environment variable before starting the program (e.g: `export DISPLAY=:0.0`).

**Comment by driofrio** [comment]
Ok, after too many hours fighting with this, the problem was that I'm using
Clion to develop.

When I opened the builded app from Xquartz it wors fine, so I realize than
Clion in new MacOs is not checking DISPLAY=:0, though manually running
Xquartz in the terminal that variable is changed to DISPLAY=:0 but in
Clion it kept saying it's empty.

So, I tried using a Docker, but to many work.

But the solution was easier, just using setenv("DISPLAY", "127.0.0.1:0",
true); inside main function, and opening xquartz manually.

Unfortunately this was not necessary before installing Ventura.

**Comment by jtsiomb** [comment]
Don't set DISPLAY to "127.0.0.1:0", you're forcing it to connect to the X server over TCP/IP as if it's connecting remotely, with the GLX line protocol and indirect rendering. Set it to ":0" if you must set it to something. Also pass 0 to the last argument of setenv to avoid setting it if it's already set.
