### ISSUE TITLE
"-- Looking for XParseGeometry - found" on x86_64-w64-mingw32 target

### ISSUE THREAD

**Issue by corwinn** [FreeGLUTProject/freeglut#135]
`CHECK_FUNCTION_EXISTS(XParseGeometry   HAVE_XPARSEGEOMETRY)` is ran unconditionally and succeeds because the host happens to have it. Host: x86_64-pc-linux-musl.
cmake: `cmake ../freeglut-3.4.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$P -DCMAKE_TOOLCHAIN_FILE=$P/cmake_toolchain_file -DCMAKE_CROSSCOMPILING=True`
Toolchain file:
`set(CMAKE_SYSTEM_NAME Windows)`
`set(CMAKE_SYSTEM_PROCESSOR x86_64)`
...
.
A simple:
`IF (NOT WIN32)`
`CHECK_FUNCTION_EXISTS(XParseGeometry   HAVE_XPARSEGEOMETRY)`
`ENDIF()`
workarounds the issue.

Thank you for "FreeGLUT".

**Comment by jtsiomb** [comment]
Wait, are you saying that you're cross-compiling for windows, but the cmake "check_whatever" look for functions in the host? not the target? I don't think that should be the case. What's your toolchain file? Is it the `mingw_cross_toolchain.cmake` file we're distributing or something else?

If the toolchain is set up correctly to look for capabilities of the target in cross-compiling environments, then all such checks should be unconditional. If the target has something, we should use it.

**Comment by corwinn** [comment]
"$P/cmake_toolchain_file" (not yours):
`set(CMAKE_SYSTEM_NAME Windows)`
`set(CMAKE_SYSTEM_PROCESSOR x86_64)`
`set(CMAKE_SYSROOT /mnt/workspace/installed64/mingw64)`
`set(tools /mnt/workspace/installed64/llvm64-14.0.6gpc)`
`set(CMAKE_C_COMPILER ${tools}/bin/x86_64-w64-mingw32-clang)`
`set(CMAKE_AR ${tools}/bin/x86_64-w64-mingw32-ar)`
`set(CMAKE_RANLIB ${tools}/bin/x86_64-w64-mingw32-ranlib)`
`set(CMAKE_CXX_COMPILER ${tools}/bin/x86_64-w64-mingw32-clang++)`
`set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)`
`set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)`
`set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)`
`set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)`
`set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)`

The file above was used to build the "compiler-rt", "libunwind", "libcxxabi" and "libcxx" parts of the mingw64 sysroot.

> cross-compiling for windows

yes
>  the cmake "check_whatever" look for functions in the host

yes:
`grep -A1 XParseGeometry CMakeFiles/CMakeOutput.log`:
`... -DCHECK_FUNCTION_EXISTS=XParseGeometry ... -c /usr/share/cmake-3.18/Modules/CheckFunctionExists.c`
.
.
BTW: It builds just fine (all the .exe at $BUILD_DIR/bin/ work flawlessly on "windows" - both the static and non-static ones) with the workaround. The program using  it, works almost as expected (the mouse pointer doesn't get hidden; the Open GL init. and rendering is just fine), but I can't state if its a "freeglut" or my issue yet.

**Comment by jtsiomb** [comment]
I'm not very familiar with cmake, so I can't be certain. Can you try simplifying the cmake toolchain file? Use the one provided by freeglut, modified to use your clang compiler and your sysroot, and see if the problem still occurs.

So basically (unless I'm missing something) just:

    SET(CMAKE_SYSTEM_NAME Windows)
    IF("${GNU_HOST}" STREQUAL "")
        SET(GNU_HOST x86_64-w64-mingw32)
    ENDIF()
    SET(CMAKE_C_COMPILER  ${GNU_HOST}-clang)
    SET(CMAKE_RC_COMPILER ${GNU_HOST}-windres)
    SET(CMAKE_SYSROOT /mnt/workspace/installed64/mingw64)

**Comment by corwinn** [comment]
"-- Looking for XParseGeometry - not found"
You made your point.
Thank you.
