### ISSUE TITLE
X11 fgPlatformGetModifiers handles super modifier incorrectly

### ISSUE THREAD

**Issue by selendym** [FreeGLUTProject/freeglut#142]
Hello.

`fgPlatformGetModifiers` in src/x11/fg_main_x11.c uses `Mod2Mask` for super: https://github.com/FreeGLUTProject/freeglut/blob/master/src/x11/fg_main_x11.c#L138-L139
Mod2 is usually mapped to num lock, while Mod4 is usually mapped to super, so this is especially problematic for those that have num lock enabled by default.

An easy fix would be to just change `Mod2Mask` to `Mod4Mask` for non-macos X11, assuming `Mod2Mask` works correctly for macos.

Related:
- issue: https://github.com/FreeGLUTProject/freeglut/issues/94#issuecomment-1060233412
- commit: https://github.com/FreeGLUTProject/freeglut/commit/0fcff8c3ccf56e112c0da95e48c3102f87e9f4bb
- some background: https://unix.stackexchange.com/a/119219
- mupdf issue: https://bbs.archlinux.org/viewtopic.php?id=281705

Best regards.

**Comment by jtsiomb** [comment]
You're absolutely right. I doubt it works correctly on macos either. It's the least tested of our platforms.
