### ISSUE TITLE
freeglut-3.0.0-rc2 does not compile on Mac OS X Yosemite

### ISSUE THREAD

**Issue by dave256** [FreeGLUTProject/freeglut#27]
Or am I doing something wrong. Here is what I did:

 $ /Applications/CMake.app/Contents/bin/cmake .

~/Downloads/freeglut-3.0.0-rc2
650 iMac: $ /Applications/CMake.app/Contents/bin/cmake .
-- The C compiler identification is AppleClang 6.0.0.6000056
-- The CXX compiler identification is AppleClang 6.0.0.6000056
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.framework  
-- Looking for XOpenDisplay in /usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib
-- Looking for XOpenDisplay in /usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/X11R6/lib/libX11.dylib
-- Looking for include file /usr/X11R6/include/X11/extensions/XInput2.h
-- Looking for include file /usr/X11R6/include/X11/extensions/XInput2.h - not found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file usbhid.h
-- Looking for include file usbhid.h - not found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for XParseGeometry
-- Looking for XParseGeometry - not found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   freeglut

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/dreed/Downloads/freeglut-3.0.0-rc2

~/Downloads/freeglut-3.0.0-rc2
651 iMac: $ make
Scanning dependencies of target freeglut
[  1%] Building C object CMakeFiles/freeglut.dir/src/fg_callbacks.c.o
In file included from /Users/dreed/Downloads/freeglut-3.0.0-rc2/src/fg_callbacks.c:29:
In file included from /Users/dreed/Downloads/freeglut-3.0.0-rc2/src/fg_internal.h:192:
/Users/dreed/Downloads/freeglut-3.0.0-rc2/src/x11/fg_internal_x11.h:36:10: fatal error: 
      'GL/glx.h' file not found
# include <GL/glx.h>

```
     ^
```

1 error generated.
make[2]: **\* [CMakeFiles/freeglut.dir/src/fg_callbacks.c.o] Error 1
make[1]: **\* [CMakeFiles/freeglut.dir/all] Error 2
make: **\* [all] Error 2

---

The file is on my computer:
$ ls /usr/X11R6/include/GL
freeglut.h  glext.h     glx_mangle.h    glxtokens.h wmesa.h
freeglut_ext.h  glu.h       glxext.h    internal/
freeglut_std.h  glu_mangle.h    glxint.h    osmesa.h
gl.h        glut.h      glxmd.h     vms_x_fix.h
gl_mangle.h glx.h       glxproto.h  wglext.h

**Comment by wojdyr** [comment]
it's discussed also at https://sourceforge.net/p/freeglut/bugs/218/
CMakeLists.txt could be modified to use OpenGL from X11 by default:
```diff
--- CMakeLists.txt	2015-02-18 04:59:57.000000000 +0000
+++ CMakeLists.txt	2015-05-19 18:48:41.860362482 +0100
@@ -220,6 +220,16 @@
 IF(FREEGLUT_GLES)
   ADD_DEFINITIONS(-DFREEGLUT_GLES)
   LIST(APPEND LIBS GLESv2 GLESv1_CM EGL)
+ELSEIF(APPLE)
+  # on OSX FindOpenGL uses framework version of OpenGL, but we need X11 version
+  FIND_PATH(GLX_INCLUDE_DIR GL/glx.h
+            PATHS /opt/X11/include /usr/X11/include /usr/X11R6/include)
+  FIND_LIBRARY(OPENGL_gl_LIBRARY GL
+               PATHS /opt/X11/lib /usr/X11/lib /usr/X11R6/lib)
+  FIND_LIBRARY(OPENGL_glu_LIBRARY GLU
+               PATHS /opt/X11/lib /usr/X11/lib /usr/X11R6/lib)
+  LIST(APPEND LIBS ${OPENGL_gl_LIBRARY})
+  INCLUDE_DIRECTORIES(${GLX_INCLUDE_DIR})
 ELSE()
   FIND_PACKAGE(OpenGL REQUIRED)
   LIST(APPEND LIBS ${OPENGL_gl_LIBRARY})
```
but OTOH X11 is not installed by default on Macs nowadays, so maybe it would be better to build it without X11 (I haven't checked but I guess it should be doable) or have a cmake option to choose whether to use X11?

**Comment by Croydon** [comment]
@wojdyr This seems to be still an issue. Could you create a pull request to fix this?

**Comment by wojdyr** [comment]
@Croydon sorry, it was 3 years ago, I'm not using freeglut in my current job

**Comment by Croydon** [comment]
@wojdyr Would it be fine with you if I'm taking your changes posted above and create a pull request?

**Comment by wojdyr** [comment]
@Croydon yes, sure

**Comment by jtsiomb** [comment]
I assume this issue is out of date, since I tried compiling the current version on macos and it seems to work fine with some special care. I've added a `README.macosx` to the repo to document how to build freeglut on that system.

Closing the issue, please let us know if the problem persists.
