### ISSUE TITLE
Unable to open display on Wayland

### ISSUE THREAD

**Issue by DmitryHetman** [FreeGLUTProject/freeglut#51]
Unable to open display ''

**Comment by DmitryHetman** [comment]
It uses environment variable $DISPLAY, but should use $WAYLAND_DISPLAY, but when I set DISPLAY=$WAYLAND_DISPLAY it still not works.

**Comment by rcmaniac25** [comment]
@Tarnyko you'd be the most knowledgeable on Wayland

**Comment by Tarnyko** [comment]
@DmitryHetman 
There is a WAYLAND_DISPLAY variable, but it does not serve this purpose.
When you run your Wayland compositor (let us say, Weston), it creates a socket file named "wayland-0" in your XDG_RUNTIME_DIR folder. It is probably something like "/var/run/<uid>" if you are using systemd.
Thus, this same XDG_RUNTIME_DIR variable should point to the same directory when you running your client program.

**Comment by DmitryHetman** [comment]
XDG_RUNTIME_DIR is set of course, you can't launch compositor without it.

**Comment by Tarnyko** [comment]
Verify you compiled FreeGLUT with the -DWAYLAND definition (it doesn't support choosing X/Wayland at runtime) as specified in the docs. DISPLAY is X11-specific and should not be used at all.

**Comment by DmitryHetman** [comment]
-DWAYLAND? or -DFREEGLUT-WAYLAND=ON?

**Comment by DmitryHetman** [comment]
Where is instruction how to compile it?

**Comment by Tarnyko** [comment]
Yeah that's it. You don't expect me to remember precise keywords for a code I did 2 years ago, don't you ;-) ?
Besides, your problem is interesting. Please drop by on IRC (#wayland on freenode) if you want quality debugging. Otherwise, I'd expect you to drop full logs (compositor log, client log, environement etc) and it will be long and tiresome for us both.

**Comment by DmitryHetman** [comment]
Problem is: 3.0.0 version doesn't supports wayland, release 3.0.1 versions.

**Comment by DmitryHetman** [comment]
Also in documentation mentioned: 
Wayland: wayland (e.g., libwayland-dev and libegl1-mesa-dev on
  Debian/Ubuntu) and xkbcommon (libxkbcommon-dev /libxkbcommon-devel)
Is it all dependencies for wayland?

**Comment by Tarnyko** [comment]
See ? Everything is in the docs, how wonderful :-).
Yes 1) you'll need to compile the GitHub version 2) libegl-mesa is required for OpenGL rendering under Wayland, xkbcommon for keymap translation because Wayland does not provide it

**Comment by DmitryHetman** [comment]
How soon new version will be released?

**Comment by dcnieho** [comment]
There is no clear roadmap now, but perhaps we should discuss doing something over the summer. In any case, do feel free to use the github version, code in the master branch there is stable, not experimental.
