### ISSUE TITLE
screen flickering resolution in non-glut applications

### ISSUE THREAD

**Issue by mgood7123** [FreeGLUTProject/freeglut#85]
how does GLUT internally handle screen flickering?

for example, when quickly resizing an X11 window, its screen will flicker black as it is resized, this DOES NOT happen when using GLUT

what does GLUT do to fix this?

**Comment by rcmaniac25** [comment]
Is this an issue with GLUT? Otherwise it may just be how whatever X11 window you're looking at is rendered/painted.
