### ISSUE TITLE
3.2.2: compile time warnings

### ISSUE THREAD

**Issue by kloczek** [FreeGLUTProject/freeglut#97]
* OS: Linux x86/64
* FreeGLUT version 
* gcc 12.0.1

freeglut compiled with LTO.
Summary stats:
```console
[tkloczko@devel-g2v SPECS]$ rpmbuild -ba --with check --with failing_tests freeglut.spec --quiet 2>&1 | grep -- -W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr
    391 -Wunused-const-variable=
      9 -Wlto-type-mismatch
      2 -Wunused-result
      1 -Wunused-but-set-variable
```
Most important are `-Wlto-type-mismatch` because those warnings are trashing LTO.

Extracted stderr with warnings: [freeglut.txt](https://github.com/dcnieho/FreeGLUT/files/8165760/freeglut.txt)

IMO it would be good as well merge openglut documentation from openglut from https://downloads.sf.net/openglut/

**Comment by jtsiomb** [comment]
From a cursory look, and if the comments in `src/x11/fg_glutfont_definitions_x11.c` are to be trusted, I don't see a way to fix the type mismatch warning while still maintaining binary compatibility with the original GLUT. I haven't checked myself to see what GLUT does and if indeed this hack is warranted. Maybe I should do that at some point to verify the claim... But for now I'm not very keen to touch this until I find time to investigate further.

**Comment by thesamesam** [comment]
See also: https://github.com/FreeGLUTProject/freeglut/pull/111

**Comment by jtsiomb** [comment]
I assume this has been fixed by commit 8c6f6bf, so I'm closing it. Feel free to re-open if it's not.

**Comment by kloczek** [comment]
Any plans to make the new release? 🤔

**Comment by jtsiomb** [comment]
We probably should. Certainly in the next couple of months we should prepare a new release.

**Comment by kloczek** [comment]
Anything more still is on outstanding list? 🤔

**Comment by jtsiomb** [comment]
There are couple of things I wanted to look into and potentially fix soon. One is about a discussion I started in the mailing list, the other about unimplemented colormap management calls. If nothing happens, I'll just push for a release next month.
